version: "3"
services:

  nginx:
    image: nginx:1.13.3
#    build:
#      context: .
#      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
        - ./files/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 1024M
#      reservations:
#        cpus: '0.10'
#        memory: 500M
#    depends_on:
#      - frontend

volumes:
  data: {}
