version: "3"
services:

  frontend:
    image: fulv/project-frontend:14.8.1
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_DEV_PROXY_API_PATH: http://backend:8080/Plone
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    networks:
      - app

  backend:
    image: fulv/project-backend:6.0.0a3
    environment:
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='db' password='plone'"
      APPLY_PROFILES: "plone.app.contenttypes:plone-content,plone.restapi:default,plone.volto:default-homepage"
      SITE: Plone
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    networks:
      - app

  db:
    image: postgres
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - app

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 500M
    depends_on:
      - frontend
    networks:
      - app

volumes:
  data: {}

networks:
  app:
