version: "3"
services:

  frontend:
    image: fulv/project-frontend:14.8.1
    container_name: frontend
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_DEV_PROXY_API_PATH: http://backend:8080/Plone
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend

  backend:
    image: fulv/project-backend:6.0.0a3
    container_name: backend
    environment:
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='db' password='plone'"
      APPLY_PROFILES: "plone.app.contenttypes:plone-content,plone.restapi:default,plone.volto:default-homepage"
      SITE: Plone
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  nginx:
    image: nginx
    container_name: nginx
    env_file:
      - ./.env
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    env_file:
      - ./.env
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    restart: always
    depends_on:
      - nginx-proxy

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    depends_on:
      - nginx

volumes:
  data: {}
  vhost:
  certs:
  acme:
  html:

# References:
# https://alexgallacher.com/how-to-setup-nginx-ssl-on-docker/
# https://hub.docker.com/r/nginxproxy/acme-companion
# https://github.com/nginx-proxy/nginx-proxy
#
