- hosts: "all"
  gather_facts: True
  become: yes

  tasks:
  - name: Install Packages
    ansible.builtin.apt:
      name:
        - docker.io
        - python3-pip
      state: present
      update_cache: yes

  - name: Install Docker Python Packages
    ansible.builtin.pip:
      name:
        - docker
        - docker-compose
      state: present

  - name: Create user plone
    ansible.builtin.user:
      name: plone
      comment: Plone User
      groups:
        - docker
      shell: '/bin/bash'
      remove: yes
      append: yes
      state: present

  - name: Set SSH Key for plone
    ansible.builtin.authorized_key:
      user: plone
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub' )}}"
      state: present

  - name: Create Project directory
    ansible.builtin.file:
      dest: /home/plone/project/
      state: directory
      owner: plone
      group: plone
      mode: 0750

  - name: Copy configuration
    ansible.builtin.copy:
      src: ./docker-compose.yml
      dest: /home/plone/project/docker-compose.yml
      owner: plone
      group: plone
      mode: 0640

  - name: Copy nginx configuration
    ansible.builtin.copy:
      src: ./nginx.yml
      dest: /home/plone/project/nginx.yml
      owner: plone
      group: plone
      mode: 0640

  - name: Copy nginx certs
    ansible.builtin.copy:
      src: ./nginx/certs/
      dest: /home/plone/project/nginx/certs/
      owner: plone
      group: plone
      mode: 0640

  - name: Copy nginx dockerfile
    ansible.builtin.copy:
      src: ./Dockerfile-nginx
      dest: /home/plone/project/Dockerfile-nginx
      owner: plone
      group: plone
      mode: 0640

  - name: Copy nginx configuration
    ansible.builtin.copy:
      src: files/nginx/default.conf
      dest: /home/plone/project/default.conf
      mode: '0644'
